### PR TITLE
Added functions to set github statuses

### LINKED ISSUE #3: Add responder for github
**Description of the problem**
The CI server currently does not support to set the status of the affected commit triggered by the github webhook.

**Description of the solution**
Throughout the github API, I will set the status of the commit by doing a HTTP POST request.

### PR DESCRIPTION
**Pull request by francislaus**
Added the two functions doRequest and doJSON, which send a HTTP POST request to set the status of commit according to the JSON data.

This should resolve #3

### CODE REVIEW

**Review by apeinot — APPROVED** [review]
Looks good. Test and functions are well documented. Nice green check on the initial commit of the repo. This should resolve #3

**Review by Jonagoo — APPROVED** [review]
Looks good, only thing is maybe the class shouldn't be named "RequestTest" if it's the final version? Or did I misinterpret it?

**Comment by apeinot** [comment]
> Looks good, only thing is maybe the class shouldn't be named "RequestTest" if it's the final version? Or did I misinterpret it?

I didn't notice that. I agree with @Jonagoo, you should rename your class and your file (it's confusing with the convension for test classes)

**Comment by francislaus** [comment]
@Jonagoo it is not the final version for the project itself. I plan on opening a new issue to move content to the class created by @emilelmarsson and also move the test to another file, which results in a single test module for the responders.

**Comment by Samuelhertzberg** [comment]
Apart fom what @Jonagoo said, it looks nice.

**Pull request merged**
