### PR TITLE
Add function to run commands

### LINKED ISSUE #4: Add code execution feature
**Description of the problem**
We need to execute some command to compile and run tests on the server

**Description of the solution**
Write a function that execute code and save both stdout and stderr in a file

### PR DESCRIPTION
**Pull request by apeinot**
Add execute function that run a command and write the output in a file.
Add the corresponding tests.

This should resolve #4

### CODE REVIEW

**Comment by apeinot** [comment]
I think the following succession of command should be executed in the CI process:

git clone $url_repo

In $repo_directory: (specify it when calling execute)
git checkout $commit_id
ant compile
ant test-compile
ant test

rm -r $repo_directory

(Only consider the result from the 3 ant command for the return status)

**Comment by francislaus** [comment]
The logic you are referring to hasn't been implemented yet, right?
The implementation of the function itself and the test case looks fine in my opinion.

**Comment by apeinot** [comment]
> The logic you are referring to hasn't been implemented yet, right?

No, this succession of command is just an hint for the issue #5 that @Jonagoo will do to connect the whole process.

**Review by emilelm96 — APPROVED** [review]
Looks good

**Review by francislaus — APPROVED** [review]

**Comment by apeinot** [comment]
I just remember that we can't change directory with 'cd' in a subprocess.
I have adapt my code to execute command in the directory we want. (I have update my hint comment accordingly)
Please add a new comment so I can merge.

**Review by emilelm96 — APPROVED** [review]
It looks good, although there is some code duplication, but I guess that's fine.

**Comment by apeinot** [comment]
> It looks good, although there is some code duplication, but I guess that's fine.

I have duplicate it just to have one version with dir and one without

**Pull request merged**
